CUDA_VISIBLE_DEVICES=0 python train_bt.py \
    --mlflow_tag random_run \
    --task_type em \
    --task Abt-Buy \
    --logdir result_em/ \
    --ssl_method combined \
    --bootstrap \
    --clustering \
    --multiplier 10 \
    --batch_size 64 \
    --lr 5e-5 \
    --lm roberta \
    --n_ssl_epochs 3 \
    --n_epochs 50 \
    --max_len 128 \
    --da cutoff \
    --size 500 \
    --fp16 \
    --run_id 4
